config/routes.rb
Rails.application.routes.draw do

  root 'carts#index'

  devise_for :users
  resources :carts
  resources :shops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def clone
    @cart = @shop.clone
    @cart.save
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  def cartsum
    cartsum = Cart.sum(:price);
  end
  
end

app/models/shop.rb
class Shop < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name] )
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def index
    @carts = current_user.carts
  end

  def show
  end


  def new
    @cart = current_user.carts.new
  end

  def create
    @cart = current_user.carts.new(cart_params)
    if @cart.save 
      redirect_to @cart, notice: 'Cart account was successfully created.'
    else 
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end

  private

    def set_cart
      @cart = current_user.carts.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:name, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
      @shops = Shop.all
    end

  def show
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to @shop
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render :new
    end
  end

  def destroy
    @shop.destroy
    redirect_to root_path
  end

  def copy
    @cart = Shop.find(params[:id])
    @shop = @cart.dup
    render './carts/new'
  end

  private
  def shop_params
    params.require(:shop).permit(:name, :price)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h2><%= @carts.length <= 0 ? "Add items to your cart!" : '' %></h2>

 <table class="highlight">
        <thead>
          <tr>
              <th>Item Name</th>
              <th>Item Price</th>
          </tr>
        </thead>

        <tbody>
          <% @carts.each do |c| %>
          <tr>
            <td><%= link_to c.name, c %></td>
            <td>$<%= c.price%></td>
          </tr>
            <% end %>
            <tr>
            <td><b>Total</b></td>
            <td><b>$<%= Cart.sum(:price) %></b></td>
          </tr> 
        </tbody>
      </table>


<hr>




<%= link_to 'Add Cart Item', new_cart_path %>

app/views/carts/new.html.erb
<%= form_for @cart do |f| %>
    <div class="form">
        <div class="form-item mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.label :price %>
            <%= f.text_field :price, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.submit%>
        </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<h1>Cart Item Details</h1>

<%= @cart.name %>
$<%= @cart.price %>

<%= link_to 'Back', root_path %> |
<%= link_to 'Update Cart Item Details', edit_cart_path %> |
<%= link_to 'Delete', @cart, method: :delete %>

app/views/layouts/_navbar.html.erb
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo"><i class="fab fa-app-store fa-2x"></i></a>
      <ul class="right hide-on-med-and-down">
      <li> <%= link_to 'Shop', shops_path %> </li>
      <!--  <li><a class="waves-effect waves-light btn">Button</a></li> -->
        <li><%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn-large' %></li>
        <li><button class="waves-effect waves-light btn-large">
             <%= link_to root_path do %>
            <i class="fas fa-shopping-cart"></i>
            <% end %>
        </button></li>

    
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<script src="https://kit.fontawesome.com/f7bc76f4fa.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>

 <table class="highlight">
        <thead>
          <tr>
              <th>Item Name</th>
              <th>Item Price</th>
          </tr>
        </thead>

        <tbody>
          <% @shops.each do |s| %>
          <tr>
            <td><%= link_to s.name, s %></td>
            <td>$<%= s.price%></td>
          </tr>
            <% end %>
           <!--  <tr>
            <td><b>Total</b></td>
            <td><b>$<%= Cart.sum(:price) %></b></td>
          </tr> -->
        </tbody>
      </table>

<%= link_to 'Add Shop Item', new_shop_path %>

app/views/shops/new.html.erb
<%= form_for @shop do |f| %>
    <div class="form">
        <div class="form-item mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.label :price %>
            <%= f.text_field :price, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.submit%>
        </div>
  </div>
<% end %>

app/views/shops/show.html.erb
<h1>Shops#show</h1>
<p>Find me in app/views/shops/show.html.erb</p>

<%= @shop.name %>
$<%= @shop.price %>

<%= link_to 'Back', root_path %> |
<%= link_to 'Update Shop Item Details', edit_shop_path %> |
<%= link_to 'Delete', @shop, method: :delete %>